# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_water.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_water(object):
    def setupUi(self, water):
        water.setObjectName("water")
        water.resize(800, 480)
        water.setStyleSheet("")
        self.btn_custom = QtWidgets.QPushButton(water)
        self.btn_custom.setGeometry(QtCore.QRect(0, 400, 268, 80))
        self.btn_custom.setStyleSheet("border-image: url(:/water/Ui/main/btn_custom.jpg);")
        self.btn_custom.setText("")
        self.btn_custom.setObjectName("btn_custom")
        self.btn_water = QtWidgets.QPushButton(water)
        self.btn_water.setGeometry(QtCore.QRect(268, 400, 268, 80))
        self.btn_water.setStyleSheet("border-image: url(:/water/Ui/main/btn_water.jpg);")
        self.btn_water.setText("")
        self.btn_water.setObjectName("btn_water")
        self.btn_help = QtWidgets.QPushButton(water)
        self.btn_help.setGeometry(QtCore.QRect(536, 400, 268, 80))
        self.btn_help.setStyleSheet("border-image: url(:/water/Ui/main/btn_help.jpg);")
        self.btn_help.setText("")
        self.btn_help.setObjectName("btn_help")
        self.label_water_main = QtWidgets.QLabel(water)
        self.label_water_main.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.label_water_main.setStyleSheet("border-image: url(:/water/Ui/water/1.jpg);")
        self.label_water_main.setText("")
        self.label_water_main.setObjectName("label_water_main")
        self.label_temp = QtWidgets.QLabel(water)
        self.label_temp.setGeometry(QtCore.QRect(330, 80, 121, 101))
        self.label_temp.setStyleSheet("font: 75 80pt \"微软雅黑\";\n"
"color: rgb(230, 0, 18);")
        self.label_temp.setObjectName("label_temp")
        self.label_temp_2 = QtWidgets.QLabel(water)
        self.label_temp_2.setGeometry(QtCore.QRect(470, 110, 38, 33))
        self.label_temp_2.setStyleSheet("border-image: url(:/water/Ui/water/单位_03.png);")
        self.label_temp_2.setText("")
        self.label_temp_2.setObjectName("label_temp_2")
        self.label_water_main.raise_()
        self.btn_custom.raise_()
        self.btn_help.raise_()
        self.btn_water.raise_()
        self.label_temp.raise_()
        self.label_temp_2.raise_()

        self.retranslateUi(water)
        QtCore.QMetaObject.connectSlotsByName(water)

    def retranslateUi(self, water):
        _translate = QtCore.QCoreApplication.translate
        water.setWindowTitle(_translate("water", "window_water"))
        self.label_temp.setText(_translate("water", "98"))
import water_rc
